spring:
  application:
    name: repatch

  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          default_batch_fetch_size: 100
      open-in-view: false

decorator:
  datasource:
#    driver-class-name: ${POSTGRESQL_DRIVER}
#    url: ${POSTGRE_URL}
#    username: ${POSTGRE_USERNAME}
#    password: ${POSTGRE_PASSWORD}
    p6spy:
      enable-logging: true

logging:
  discord:
    webhook-uri: ${DISCORD_WEBHOOK_URL}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}