spring:
  application:
    name: refab

decorator:
  datasource:
#    driver-class-name: ${POSTGRESQL_DRIVER}
#    url: ${POSTGRE_URL}
#    username: ${POSTGRE_USERNAME}
#    password: ${POSTGRE_PASSWORD}
    p6spy:
      enable-logging: true

logging:
  discord:
    webhook-uri: ${DISCORD_WEBHOOK_URL}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}