spring:
  application:
    name: repatch

  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          default_batch_fetch_size: 100
      open-in-view: false

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  discord:
    webhook-uri: ${DISCORD_WEBHOOK_URL}
