spring:
  application:
    name: refab

  datasource:
    url: jdbc:postgresql://localhost:5432/yourdatabase
    username: youruser
    password: yourpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create